extends:
  - stylelint-config-standard
  - stylelint-config-recommended-scss
  - stylelint-config-recess-order
  - stylelint-config-prettier
plugins:
  - stylelint-scss
rules:
  declaration-colon-newline-after: null
  value-list-comma-newline-after: null
  no-duplicate-selectors: null
